### PR TITLE
Issue #18 41-TET

### PR DESCRIPTION
**Pull request by tristantarrant**
https://github.com/brummer10/guitarix/issues/19

### CODE REVIEW

**Comment by brummer10** [comment]
Very nice, thanks a lot!

**Comment by lafrech** [comment]
Looks the wrong issue was mentioned in the OP, and therefore closed by mistake.

**Comment by brummer10** [comment]
Looks like. 
Anyway, guitarix is now available as vst3 plugin, allow you to direct load your presets into the DAW and do automation on any parameter. So I guess issue #19 could be marked as done.
https://github.com/brummer10/guitarix.vst

**Comment by lafrech** [comment]
Oh, that's good news. Thanks for the work on this!

**Pull request merged**
