### PR TITLE
French translation update to 100%

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by brummer10** [comment]
The  mnemonic key's looks wrong for the menu entry's. They should match the one in the original string, or don't be there at all. 
Still I'll merge this PR, but you may like to correct that before we release.

regards
hermann

**Comment by trebmuh** [comment]
I assume you're talking about the "_" sign (such as "_Q" for Quit).

I don't understand why you say:
> They should match the one in the original string, or don't be there at all.

In all the translations I've seen so far, when a letter used for a mnemonic in the English string isn't present in its translation strings, then we're leaved with a choice :
1. keep the same mnemonic in parenthesis, such as: "_Quit" -> "Sortir (_Q)"
2. use another letter, such as "_Quit" -> "_Sortir"

The second choice is better for the user since it's more natural. But we have to take care about not clashing with another already used mnemonic. Which I've only did partially so far.

I'll have a precise look at the mnemonics today.

**Comment by brummer10** [comment]
That' what I mean, I see of lot of duplicated mnemonics in the translation.

**Comment by trebmuh** [comment]
I found 9 of these, see the #42 PR. Did you see any other?

**Pull request merged**
