### PR TITLE
Improved tube stage

### PR DESCRIPTION
**Pull request by zamaudio**
- Add resistor in series Ra = d(Vp)/d(Ip)
- Add Ranode tables for looking up the plate resistance
- Missing 6V6 tube specs so new table is wrong for this tube
- Converted tube_transfer.py to python3

Signed-off-by: Damien Zammit <damien@zamaudio.com>

### CODE REVIEW

**Comment by brummer10** [comment]
Hi
Finlay found the time to checkout your PR. Thanks for that.
While the changes sound nice so far, I've a issue with the produced dc-offset.  
So this implementation requires a final dcblocker. I've implement  : fi.dcblockerat(1.0) to remove the offset.

To the 6V6 tube tables, unfortunately we can't rebuild them, as we've lost the specs for it, and, it required a slightly change in  tube_transfer.py (which we've also lost. 
So I reimplement the old tubestageF as tubestage6V6F definition for use it with the 6V6 tubes only. 

regards
hermann

**Comment by zamaudio** [comment]
@brummer10 i think `tb` is an integer that selects which tube model, I don't think its the input signal (?)  If I am right, then it makes very little sense to use `tb*`

**Comment by zamaudio** [comment]
I think i fixed the DC offset problem in the commits that you merged already, I don't think you need the dc blocker, but I could be wrong.

**Comment by brummer10** [comment]
@zamaudio 
Ups, yes. it is the tube selector. Makes no sense to use it here.
Just the DC offset is still there.

**Comment by brummer10** [comment]
so this one will use the input 
`tube(x) = x:(+ : (tubeVp)) ~ (x*(Rk/(Rp + Ranode(tb)))) : /(divider);`

**Pull request merged**
